# Generated by Django 2.0 on 2018-01-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Medication/Sponse'), ('2', 'Adoption'), ('3', 'Donation'), ('4', 'About US'), ('5', 'Contact US')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('amount', models.PositiveIntegerField(default=111)),
            ],
        ),
        migrations.CreateModel(
            name='PageQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField(max_length=10000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('profession', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=13)),
                ('alt_phone_no', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=250)),
                ('nationality', models.CharField(max_length=100)),
                ('joining_reason', models.TextField(verbose_name='Why should you join Friends For Animal?')),
                ('hearing_mode', models.CharField(max_length=120, verbose_name='How did you hear about us?')),
            ],
        ),
    ]
