# Generated by Django 2.0 on 2017-12-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171221_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('amount', models.PositiveIntegerField(default=111)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('1', 'Medication/Sponse'), ('2', 'Adoption'), ('3', 'Donation')], max_length=1, unique=True),
        ),
    ]
