# Generated by Django 2.0 on 2017-12-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171224_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('profession', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=13)),
                ('alt_phone_no', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=250)),
                ('nationality', models.CharField(max_length=100)),
                ('joining_reason', models.TextField(verbose_name='Why do you want to join?')),
                ('hearing_mode', models.CharField(max_length=120, verbose_name='How did you hear about us?')),
            ],
        ),
    ]
