# Generated by Django 2.0 on 2018-01-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180107_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=13)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
    ]
