# Generated by Django 2.0 on 2018-01-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='background_image',
            field=models.ImageField(default='/media/images/fbook.png', upload_to='uploads/blogs/'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(default='/media/images/fbook.png', upload_to='uploads/blogs/'),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='/media/images/fbook.png', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
